[project]
name = "magisk-channel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browserforge>=1.2.3",
    "curl-cffi>=0.13.0",
    "dotenv>=0.9.9",
    "pydantic>=2.11.7",
]
